name: fortis
description: High-level cryptography for Dart. Fluent builder API with compile-time safety, sane defaults, and seamless cross-platform interoperability.
version: 0.1.0
homepage: https://github.com/edunatalec/fortis
repository: https://github.com/edunatalec/fortis
issue_tracker: https://github.com/edunatalec/fortis/issues

environment:
  sdk: ^3.11.0

dependencies:
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0

topics:
  - cryptography
  - encryption
  - security
