import 'dart:convert';
import 'dart:typed_data';

import '../../exceptions/fortis_key_exception.dart';

/// An AES symmetric key used for both encryption and decryption.
///
/// AES is a symmetric cipher — the same key encrypts and decrypts.
/// Supported key sizes are 128, 192, and 256 bits.
///
/// To generate a key, use the builder (defaults to 256 bits):
/// ```dart
/// final key = await Fortis.aes().generateKey();
/// ```
///
/// To import an existing key, use [fromBytes] or [fromBase64].
class FortisAesKey {
  final Uint8List _bytes;

  FortisAesKey._(this._bytes);

  /// The key size in bits — 128, 192, or 256.
  ///
  /// Example:
  /// ```dart
  /// final key = await Fortis.aes().keySize(192).generateKey();
  /// print(key.keySize); // 192
  /// ```
  int get keySize => _bytes.length * 8;

  /// Returns a copy of the raw key bytes (16, 24, or 32 bytes).
  ///
  /// Example:
  /// ```dart
  /// final bytes = key.toBytes(); // Uint8List
  /// storeRaw(bytes);             // persist somewhere safe
  /// ```
  Uint8List toBytes() => Uint8List.fromList(_bytes);

  /// Encodes the key as a Base64 string — convenient for storage in .env
  /// files, databases, or JSON.
  ///
  /// Example:
  /// ```dart
  /// final encoded = key.toBase64(); // 'h0FJ...=='
  /// final roundtrip = FortisAesKey.fromBase64(encoded);
  /// ```
  String toBase64() => base64Encode(_bytes);

  /// Imports an AES key from raw bytes.
  ///
  /// The byte length must correspond to a valid AES key size:
  /// - 16 bytes → 128-bit key
  /// - 24 bytes → 192-bit key
  /// - 32 bytes → 256-bit key
  ///
  /// Example:
  /// ```dart
  /// final key = FortisAesKey.fromBytes(myRandomBytes); // must be 16/24/32
  /// ```
  ///
  /// Throws [FortisKeyException] if the byte length is not valid.
  factory FortisAesKey.fromBytes(Uint8List bytes) {
    final bits = bytes.length * 8;

    if (bits != 128 && bits != 192 && bits != 256) {
      throw FortisKeyException(
        'Invalid AES key size: $bits bits. '
        'Must be 128, 192, or 256 bits (16, 24, or 32 bytes).',
      );
    }

    return FortisAesKey._(Uint8List.fromList(bytes));
  }

  /// Imports an AES key from a Base64-encoded string.
  ///
  /// Example:
  /// ```dart
  /// final key = FortisAesKey.fromBase64(envVar('AES_KEY_B64'));
  /// ```
  ///
  /// Throws [FortisKeyException] if the string is not valid Base64, or if
  /// the decoded length is not a valid AES key size.
  factory FortisAesKey.fromBase64(String b64) {
    try {
      final bytes = base64Decode(b64);

      return FortisAesKey.fromBytes(bytes);
    } on FortisKeyException {
      rethrow;
    } catch (e) {
      throw FortisKeyException('Invalid Base64 for AES key: $e');
    }
  }

  /// Internal constructor for trusted key bytes (generated by the builder).
  static FortisAesKey fromTrustedBytes(Uint8List bytes) =>
      FortisAesKey._(bytes);
}
