import 'dart:convert';
import 'dart:typed_data';

import '../../exceptions/fortis_key_exception.dart';

/// An AES symmetric key used for both encryption and decryption.
///
/// AES is a symmetric cipher — the same key encrypts and decrypts.
/// Supported key sizes are 128, 192, and 256 bits.
///
/// To generate a key, use the builder:
/// ```dart
/// final key = await Fortis.aes().keySize(256).generateKey();
/// ```
///
/// To import an existing key, use [fromBytes] or [fromBase64].
class FortisAesKey {
  final Uint8List _bytes;

  FortisAesKey._(this._bytes);

  /// The key size in bits (128, 192, or 256).
  int get keySize => _bytes.length * 8;

  /// Returns a copy of the raw key bytes.
  Uint8List toBytes() => Uint8List.fromList(_bytes);

  /// Encodes the key as a Base64 string.
  String toBase64() => base64Encode(_bytes);

  /// Imports an AES key from raw bytes.
  ///
  /// Throws [FortisKeyException] if the byte length does not correspond
  /// to a valid AES key size (16, 24, or 32 bytes).
  factory FortisAesKey.fromBytes(Uint8List bytes) {
    final bits = bytes.length * 8;
    if (bits != 128 && bits != 192 && bits != 256) {
      throw FortisKeyException(
        'Invalid AES key size: $bits bits. '
        'Must be 128, 192, or 256 bits (16, 24, or 32 bytes).',
      );
    }
    return FortisAesKey._(Uint8List.fromList(bytes));
  }

  /// Imports an AES key from a Base64-encoded string.
  ///
  /// Throws [FortisKeyException] if the string is not valid Base64,
  /// or if the decoded length is not a valid AES key size.
  factory FortisAesKey.fromBase64(String b64) {
    try {
      final bytes = base64Decode(b64);
      return FortisAesKey.fromBytes(bytes);
    } on FortisKeyException {
      rethrow;
    } catch (e) {
      throw FortisKeyException('Invalid Base64 for AES key: $e');
    }
  }

  /// Internal constructor for trusted key bytes (e.g., generated by the builder).
  static FortisAesKey fromTrustedBytes(Uint8List bytes) =>
      FortisAesKey._(bytes);
}
